In [81]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.preprocessing import OrdinalEncoder
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory


# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [82]:
df = pd.read_csv('/kaggle/input/diabetes-prediction-dataset/diabetes_prediction_dataset.csv')

In [83]:
df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [84]:
df.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [85]:
# Define the mapping
mapping = {'Male': 0, 'Female': 1}

# Fill NaN values in 'gender' column with 'unknown'
df['gender'] = df['gender'].fillna('unknown')

# Apply label encoding
df['gender_encoded'] = df['gender'].map(mapping)

In [86]:
df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes,gender_encoded
0,Female,80.0,0,1,never,25.19,6.6,140,0,1.0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0,1.0
2,Male,28.0,0,0,never,27.32,5.7,158,0,0.0
3,Female,36.0,0,0,current,23.45,5.0,155,0,1.0
4,Male,76.0,1,1,current,20.14,4.8,155,0,0.0
...,...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0,1.0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0,1.0
99997,Male,66.0,0,0,former,27.83,5.7,155,0,0.0
99998,Female,24.0,0,0,never,35.42,4.0,100,0,1.0
99999,Female,57.0,0,0,current,22.43,6.6,90,0,1.0

In [87]:
df.isnull().sum()

gender                  0
age                     0
hypertension            0
heart_disease           0
smoking_history         0
bmi                     0
HbA1c_level             0
blood_glucose_level     0
diabetes                0
gender_encoded         18
dtype: int64

In [88]:
for column in df.columns[df.isnull().any()]:
    mode_value = df[column].mode()[0]
    df[column]=df[column].fillna(mode_value)

In [89]:
df.drop('gender' , axis = 1)

,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes,gender_encoded
0,80.0,0,1,never,25.19,6.6,140,0,1.0
1,54.0,0,0,No Info,27.32,6.6,80,0,1.0
2,28.0,0,0,never,27.32,5.7,158,0,0.0
3,36.0,0,0,current,23.45,5.0,155,0,1.0
4,76.0,1,1,current,20.14,4.8,155,0,0.0
...,...,...,...,...,...,...,...,...,...
99995,80.0,0,0,No Info,27.32,6.2,90,0,1.0
99996,2.0,0,0,No Info,17.37,6.5,100,0,1.0
99997,66.0,0,0,former,27.83,5.7,155,0,0.0
99998,24.0,0,0,never,35.42,4.0,100,0,1.0
99999,57.0,0,0,current,22.43,6.6,90,0,1.0

In [90]:
df['smoking_history'].unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

In [91]:

# Extract the smoking_history column
smoking_history_column = df['smoking_history'].values.reshape(-1, 1)

# Define the ordinal encoder
ordinal_encoder = OrdinalEncoder(categories=[['never', 'No Info', 'not current', 'former', 'current', 'ever']])

# Fit and transform the encoder to convert smoking history values
encoded_smoking_history = ordinal_encoder.fit_transform(smoking_history_column)

# Update the DataFrame with the encoded values
df['smoking_history_encoded'] = encoded_smoking_history

In [92]:
df = df.drop('gender', axis = 1)

In [93]:
 df = df.drop('smoking_history', axis = 1)

In [94]:
df

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes,gender_encoded,smoking_history_encoded
0,80.0,0,1,25.19,6.6,140,0,1.0,0.0
1,54.0,0,0,27.32,6.6,80,0,1.0,1.0
2,28.0,0,0,27.32,5.7,158,0,0.0,0.0
3,36.0,0,0,23.45,5.0,155,0,1.0,4.0
4,76.0,1,1,20.14,4.8,155,0,0.0,4.0
...,...,...,...,...,...,...,...,...,...
99995,80.0,0,0,27.32,6.2,90,0,1.0,1.0
99996,2.0,0,0,17.37,6.5,100,0,1.0,1.0
99997,66.0,0,0,27.83,5.7,155,0,0.0,3.0
99998,24.0,0,0,35.42,4.0,100,0,1.0,0.0
99999,57.0,0,0,22.43,6.6,90,0,1.0,4.0

In [95]:

from sklearn.preprocessing import MinMaxScaler

In [96]:
scaler = MinMaxScaler()

# Define which columns to scale (all numerical columns)
numerical_columns = ['age', 'hypertension', 'heart_disease', 'bmi', 'HbA1c_level', 
                     'blood_glucose_level', 'diabetes', 'gender_encoded', 'smoking_history_encoded']

# Scale the numerical columns
df[numerical_columns] = scaler.fit_transform(df[numerical_columns])

In [97]:
df

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes,gender_encoded,smoking_history_encoded
0,1.000000,0.0,1.0,0.177171,0.563636,0.272727,0.0,1.0,0.0
1,0.674675,0.0,0.0,0.202031,0.563636,0.000000,0.0,1.0,0.2
2,0.349349,0.0,0.0,0.202031,0.400000,0.354545,0.0,0.0,0.0
3,0.449449,0.0,0.0,0.156863,0.272727,0.340909,0.0,1.0,0.8
4,0.949950,1.0,1.0,0.118231,0.236364,0.340909,0.0,0.0,0.8
...,...,...,...,...,...,...,...,...,...
99995,1.000000,0.0,0.0,0.202031,0.490909,0.045455,0.0,1.0,0.2
99996,0.024024,0.0,0.0,0.085901,0.545455,0.090909,0.0,1.0,0.2
99997,0.824825,0.0,0.0,0.207983,0.400000,0.340909,0.0,0.0,0.6
99998,0.299299,0.0,0.0,0.296569,0.090909,0.090909,0.0,1.0,0.0
99999,0.712212,0.0,0.0,0.144958,0.563636,0.045455,0.0,1.0,0.8

In [98]:
df.isnull().sum()

age                        0
hypertension               0
heart_disease              0
bmi                        0
HbA1c_level                0
blood_glucose_level        0
diabetes                   0
gender_encoded             0
smoking_history_encoded    0
dtype: int64

In [99]:
X = df[['age' , 'hypertension',	'heart_disease','bmi','HbA1c_level','blood_glucose_level','gender_encoded',	'smoking_history_encoded']]

In [100]:
Y = df['diabetes']

In [101]:
from sklearn.model_selection import train_test_split

In [102]:
X_train , X_test , Y_train , Y_test = train_test_split( X ,Y , test_size = 0.3 , random_state = 42)

In [103]:
X_train.shape , X_test.shape , Y_train.shape , Y_test.shape

((70000, 8), (30000, 8), (70000,), (30000,))

In [104]:
from sklearn.linear_model import LogisticRegression

In [112]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [105]:
lrmodel = LogisticRegression()

In [108]:
lrmodel.fit(X_train , Y_train)

LogisticRegression()

In [110]:
y_pred = lrmodel.predict(X_test)

In [113]:
accuracy = accuracy_score(Y_test, y_pred)
conf_matrix = confusion_matrix(Y_test, y_pred)
classification_rep = classification_report(Y_test, y_pred)

In [114]:
print("Accuracy:", accuracy)
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)

Accuracy: 0.959
Confusion Matrix:
[[27224   229]
 [ 1001  1546]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.96      0.99      0.98     27453
         1.0       0.87      0.61      0.72      2547

    accuracy                           0.96     30000
   macro avg       0.92      0.80      0.85     30000
weighted avg       0.96      0.96      0.96     30000

In [116]:
from IPython.display import FileLink

# Assuming your DataFrame is named "df"
df.to_csv('output_file.csv', index=False)
FileLink('output_file.csv')

/kaggle/working/output_file.csv